<?php
$ann_slider_sc = ann_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $ann_slider_sc ) && strpos( $ann_slider_sc, '[' ) !== false && strpos( $ann_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( ann_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$ann_anchor_icon = ann_get_theme_option( 'front_page_title_anchor_icon' );
		$ann_anchor_text = ann_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $ann_anchor_icon ) || ! empty( $ann_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $ann_anchor_icon ) ? ' icon="' . esc_attr( $ann_anchor_icon ) . '"' : '' )
									. ( ! empty( $ann_anchor_text ) ? ' title="' . esc_attr( $ann_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $ann_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$ann_scheme = ann_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $ann_scheme ) && ! ann_is_inherit( $ann_scheme ) ) {
			echo ' scheme_' . esc_attr( $ann_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( ann_get_theme_option( 'front_page_title_paddings' ) );
		if ( ann_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$ann_css      = '';
		$ann_bg_image = ann_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $ann_bg_image ) ) {
			$ann_css .= 'background-image: url(' . esc_url( ann_get_attachment_url( $ann_bg_image ) ) . ');';
		}
		if ( ! empty( $ann_css ) ) {
			echo ' style="' . esc_attr( $ann_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$ann_anchor_icon = ann_get_theme_option( 'front_page_title_anchor_icon' );
		$ann_anchor_text = ann_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $ann_anchor_icon ) || ! empty( $ann_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $ann_anchor_icon ) ? ' icon="' . esc_attr( $ann_anchor_icon ) . '"' : '' )
									. ( ! empty( $ann_anchor_text ) ? ' title="' . esc_attr( $ann_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( ann_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' ann-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$ann_css      = '';
			$ann_bg_mask  = ann_get_theme_option( 'front_page_title_bg_mask' );
			$ann_bg_color_type = ann_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $ann_bg_color_type ) {
				$ann_bg_color = ann_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $ann_bg_color_type ) {
				$ann_bg_color = ann_get_scheme_color( 'bg_color', $ann_scheme );
			} else {
				$ann_bg_color = '';
			}
			if ( ! empty( $ann_bg_color ) && $ann_bg_mask > 0 ) {
				$ann_css .= 'background-color: ' . esc_attr(
					1 == $ann_bg_mask ? $ann_bg_color : ann_hex2rgba( $ann_bg_color, $ann_bg_mask )
				) . ';';
			}
			if ( ! empty( $ann_css ) ) {
				echo ' style="' . esc_attr( $ann_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$ann_caption = ann_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $ann_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $ann_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $ann_caption, 'ann_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$ann_description = ann_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $ann_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $ann_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $ann_description ), 'ann_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( ann_get_theme_option( 'front_page_title_button1_link' ) != '' || ann_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						ann_show_layout( ann_customizer_partial_refresh_front_page_title_button1_link() );
						ann_show_layout( ann_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
